name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      image_name:
        description: 'a'
        type: string
      working_directory:
        description: 'a'
        type: string
      dockerfile:
        description: 'a'
        type: string
      registry_container:
        description: 'a'
        type: string
      environment:
        description: 'a'
        type: string
        default: 'dev'
      # GCP_PROJECT_ID:
      #   description: 'a'
      #   type: string
      #   required: true
    secrets:
      GCP_SA_KEY:
        required: true

concurrency:
  group: ${{ inputs.github-workflow }}-${{ inputs.github-ref }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Use gcloud CLI
        run: gcloud info

      - name: Docker auth
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Build image
        working-directory: ${{ inputs.working_directory}}
        run: |
          echo ${{ env.GCP_PROJECT }}
          docker buildx build -f ${{ inputs.dockerfile }} -t ${{ inputs.image_name }} .
          docker tag ${{ inputs.image_name}} us-central1-docker.pkg.dev/${{ env.GCP_PROJECT }}/${{ inputs.registry_container}}/${{ inputs.image_name}}:latest

      - name: Push image
        run: |
          docker push us-central1-docker.pkg.dev/${{ env.GCP_PROJECT }}/${{ inputs.registry_container}}/${{ inputs.image_name}}:latest

